services:
  postgres:
    image: postgres:16-alpine
    container_name: relational_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pineapple-net

  redis:
    image: redis:7-alpine
    container_name: cache_db
    restart: always
    command: redis-server --save 60 1 --loglevel warning --requirepass ${CACHE_PASS}
    ports:
      - "${CACHE_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - pineapple-net

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: stream_db
    ports:
      - "${STREAM_PORT}:9092"
    environment:
      # P.S.: KRaft mode as broker and controller
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'

      # P.S.: KRaft Quorum instead of Zookeper
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'

      # P.S.: EXTERNAL for host access (localhost), INTERNAL for container-to-container (kafka:29092)
      KAFKA_LISTENERS: 'EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'EXTERNAL://localhost:9092,INTERNAL://kafka:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - pineapple-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: 'local-kraft-cluster'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:29092'
    networks:
      - pineapple-net


volumes:
  postgres_data: {}
  redis_data:
    driver: local
  kafka_data:
    driver: local

networks:
  pineapple-net:
    driver: bridge